### ISSUE TITLE
Go get example needs updating?

### ISSUE THREAD

**Issue by dmowcomber** [Frabjous-Studios/ingenten#1]
The `go get` example in the readme is:
`go get github.com/FrabjousStudios/ingenten`
but shouldn't it be:
`go get github.com/Frabjous-Studios/ingenten`

**Comment by dmowcomber** [comment]
Here's a pull request https://github.com/Frabjous-Studios/ingenten/pull/2

**Comment by kalexmills** [comment]
Thanks! Sorry for the delay in merging. Much appreciated.
